cultural_name_data = {
    "Western": {
        "Step Off [Western]": {
            "price": 1_500,
            "event_type": "team",
            "min_participants": 9,
            "max_participants": 15,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025 to 26/01/2025",
            "age_category": "16 to 27",
            "docs_required": "ID Proof",
        }, 
        "Footloose [Western]": {
            "price": 250,
            "event_type": "single",
            "min_participants": 1,
            "max_participants": 1,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025 to 26/01/2025",
            "age_category": "16 to 27",
            "docs_required": "ID Proof",
    },
    },
    "Art":{
        "Pixelate [Art]": {
            "price": 150,
            "event_type": "single",
            "min_participants": 1,
            "max_participants": 1,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025",
            "age_category": "17 to 27",
            "docs_required": "ID Proof",
        },
    },
   "Classical":{
    "Nritya Sangam [Classical]": {
        "price": 1_500,
        "event_type": "team",
        "min_participants": 7,
        "max_participants": 15,
        "min_managers": 0,
        "max_managers": 0,
        "date_of_event": "22/01/2025 to 26/01/2025",
        "age_category": "16 to 27",
        "docs_required": "ID Proof",
    },
    
    "Ek taal [Classical]": {
        "price": 250,
        "event_type": "single",
        "min_participants": 1,
        "max_participants": 1,
        "min_managers": 0,
        "max_managers": 0,
        "date_of_event": "22/01/2025 to 26/01/2025",
        "age_category": "16 to 27",
        "docs_required": "ID Proof",
    },
   },
    "Music":{
        "Battle of the Bands [Music]": {
            "price": 600,
            "event_type": "team",
            "min_participants": 4,
            "max_participants": 8,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025",
            "age_category": "17+",
            "docs_required": "ID Proof",
        },
        "Cadence [Music]": {
            "price": 250,
            "event_type": "single",
            "min_participants": 1,
            "max_participants": 1,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025 to 26/01/2025",
            "age_category": "17+",
            "docs_required": "ID Proof",
        },
    },
    "Photography":{
        "Drishti [Photography]": {
            "price": 250,
            "event_type": "single",
            "min_participants": 1,
            "max_participants": 1,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025 to 26/01/2025",
            "age_category": "16-27",
            "docs_required": "ID Proof",
        },
    },
    "Poetry":{
        "Kalam Ki Kala [Poetry]": {
            "price": 180,
            "event_type": "single",
            "min_participants": 1,
            "max_participants": 1,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025 to 26/01/2025",
            "age_category": "16-27",
            "docs_required": "ID Proof",
        },
    },
}       