import uuid

cultural_name_data = {
    "Western": {
        "Step Off [Western]": {
            "price": 1_500,
            "event_type": "team",
            "min_participants": 9,
            "max_participants": 15,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025 to 26/01/2025",
            "age_category": "16 to 27",
            "docs_required": "ID Proof",
            "unique_id": str(uuid.uuid4()),
        },
        "Footloose [Western]": {
            "price": 250,
            "event_type": "single",
            "min_participants": 1,
            "max_participants": 1,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025 to 26/01/2025",
            "age_category": "16 to 27",
            "docs_required": "ID Proof",
            "unique_id": str(uuid.uuid4()),
        },
    },
    "Art": {
        "Pixelate [Art]": {
            "price": 150,
            "event_type": "single",
            "min_participants": 1,
            "max_participants": 1,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025",
            "age_category": "17 to 27",
            "docs_required": "ID Proof",
            "unique_id": str(uuid.uuid4()),
        },
    },
    "Classical": {
        "Nritya Sangam [Classical]": {
            "price": 1_500,
            "event_type": "team",
            "min_participants": 7,
            "max_participants": 15,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025 to 26/01/2025",
            "age_category": "16 to 27",
            "docs_required": "ID Proof",
            "unique_id": str(uuid.uuid4()),
        },
        "Ek taal [Classical]": {
            "price": 250,
            "event_type": "single",
            "min_participants": 1,
            "max_participants": 1,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025 to 26/01/2025",
            "age_category": "16 to 27",
            "docs_required": "ID Proof",
            "unique_id": str(uuid.uuid4()),
        },
    },
    "Music": {
        "Battle of the Bands [Music]": {
            "price": 600,
            "event_type": "team",
            "min_participants": 4,
            "max_participants": 8,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025",
            "age_category": "17+",
            "docs_required": "ID Proof",
            "unique_id": str(uuid.uuid4()),
        },
        "Cadence [Music]": {
            "price": 250,
            "event_type": "single",
            "min_participants": 1,
            "max_participants": 1,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025 to 26/01/2025",
            "age_category": "17+",
            "docs_required": "ID Proof",
            "unique_id": str(uuid.uuid4()),
        },
    },
    "Photography": {
        "Drishti [Photography]": {
            "price": 250,
            "event_type": "single",
            "min_participants": 1,
            "max_participants": 1,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025 to 26/01/2025",
            "age_category": "16-27",
            "docs_required": "ID Proof",
            "unique_id": str(uuid.uuid4()),
        },
    },
    "Poetry": {
        "Kalam Ki Kala [Poetry]": {
            "price": 180,
            "event_type": "single",
            "min_participants": 1,
            "max_participants": 1,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025 to 26/01/2025",
            "age_category": "16-27",
            "docs_required": "ID Proof",
            "unique_id": str(uuid.uuid4()),
        },
    },
}
