sports_name_data = {
    "Mr and Ms Kurukshetra":{
        "Mr and Ms Kurukshetra [Male]": {
            "gender": "male",
            "price": 750,
            "event_type": "single",
            "min_participants": 1,
            "max_participants": 1,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "23/01/2025 to 24/01/2025",
            "age_category": "17 to 27",
            "docs_required": "ID Proof",
        },
        "Mr and Ms Kurukshetra [Female]": {
            "gender": "female",
            "price": 740,
            "event_type": "single",
            "min_participants": 1,
            "max_participants": 1,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "23/01/2025 to 24/01/2025",
            "age_category": "17 to 27",
            "docs_required": "ID Proof",
        },
    },
    "Cricket":{
        "Cricket [Male]": {
            "gender": "Male",
            "price": 25_000,
            "event_type": "team",
            "min_participants": 13,
            "max_participants": 16,
            "min_managers": 1,
            "max_managers": 2,
            "date_of_event": "3/01/2025 to 26/01/2025",
            "age_category": "16 to 30",
            "docs_required": "ID Proof",
        },
    },
    "Snooker":{
        "Kurukshetra Snooker Tournament  [Open]": {
            "gender": "open",
            "price": 354,
            "event_type": "single",
            "min_participants": 1,
            "max_participants": 1,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "22/01/2025 to 26/01/2025",
            "age_category": "16 to 30",
            "docs_required": "ID Proof",
        },
    },
    
    "Football": {
    "Football [Male]": {
        "gender": "male",
        "price": 9_440,
        "event_type": "team",
        "min_participants": 11,
        "max_participants": 18,
        "min_managers": 1,
        "max_managers": 2,
        "date_of_event": "15/01/2025 to 24/01/2025",
        "age_category": "15 to 27",
        "docs_required": "ID Proof",
    },
    "Football [Female]": {
        "gender": "female",
        "price": 4_130,
        "event_type": "team",
        "min_participants": 11,
        "max_participants": 18,
        "min_managers": 1,
        "max_managers": 2,
        "date_of_event": "15/01/2025 to 24/01/2025",
        "age_category": "15 to 27",
        "docs_required": "ID Proof",
    }
    }
    ,

    "Chess":{
        "Chess Team Tournament [Open]": {
            "gender": "open",
            "price": 1_500,
            "event_type": "team",
            "min_participants": 4,
            "max_participants": 4,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "26/1/2025",
            "age_category": "18 to 30",
            "docs_required": "ID Proof",
        },
    },
    
    "Esports":{
        "Esports FIFA / EA FC [Open]": {
            "gender": "open",
            "price": 300,
            "event_type": "single",
            "min_participants": 1,
            "max_participants": 1,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "20/01/2025 to 22/01/2025",
            "age_category": "18 to 30",
            "docs_required": "ID Proof",
        },
        "Esports BGMI [Open]": {
            "gender": "open",
            "price": 800,
            "event_type": "team",
            "min_participants": 4,
            "max_participants": 5,
            "min_managers": 0,
            "max_managers": 1,
            "date_of_event": "23/01/2025 to 24/01/2025",
            "age_category": "18 to 30",
            "docs_required": "ID Proof",
        },
        
    },
    
    
    "Volleyball":{
        "Volleyball [Male]": {
            "gender": "male",
            "price": 2_400,
            "event_type": "team",
            "min_participants": 6,
            "max_participants": 12,
            "min_managers": 1,
            "max_managers": 3,
            "date_of_event": "23/01/2025 to 24/01/2025",
            "age_category": "17 to 27",
            "docs_required": "ID Proof",
        },
        "Volleyball [Female]": {
            "gender": "female",
            "price": 1_600,
            "event_type": "team",
            "min_participants": 6,
            "max_participants": 12,
            "min_managers": 1,
            "max_managers": 3,
            "date_of_event": "23/01/2025 to 24/01/2025",
            "age_category": "17 to 27",
            "docs_required": "ID Proof",
        },
    },
    "Table Tennis":{
        "Table Tennis Team [Male]": {
            "gender": "male",
            "price": 1_180,
            "event_type": "team",
            "min_participants": 3,
            "max_participants": 5,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "",
            "age_category": "17 to 27",
            "docs_required": "ID Proof",
        },
        "Table Tennis Team [Female]": {
            "gender": "open",
            "price": 1000,
            "event_type": "team",
            "min_participants": 2,
            "max_participants": 2,
            "min_managers": "",
            "max_managers": "",
            "date_of_event": "",
            "age_category": "17 to 27",
            "docs_required": "ID Proof",
        },
        "Table Tennis Doubles [Male]": {
            "gender": "open",
            "price": 400,
            "event_type": "team",
            "min_participants": 2,
            "max_participants": 2,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": 0,
            "age_category": "17 to 27",
            "docs_required": "ID Proof",
        },
        "Table Tennis Mixed Doubles [Open]": {
            "gender": "open",
            "price": 400,
            "event_type": "team",
            "min_participants": 2,
            "max_participants": 2,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "",
            "age_category": "17 to 27",
            "docs_required": "ID Proof",
        },
    },
    "Zumba":{
    "Zumba Masterclass [Open]": {
        "gender": "open",
        "price": 301,
        "event_type": "single",
        "min_participants": 1,
        "max_participants": 1,
        "min_managers": 0,
        "max_managers": 0,
        "date_of_event": "",
        "age_category": "",
        "docs_required": "",
    },
    },
    "5k Hill Run":{
        "5k Hill Run [Open]": {
            "gender": "open",
            "price": 501,
            "event_type": "single",
            "min_participants": 1,
            "max_participants": 1,
            "min_managers": 0,
            "max_managers": 0,
            "date_of_event": "26/01/2025",
            "age_category": "17 to 27",
            "docs_required": "ID Proof",
        },
    },
    "Basketball":{
        "3v3 Basketball Men [Open]": {
            "gender": "male",
            "price": 2_124,
            "event_type": "team",
            "min_participants": 4,
            "max_participants": 4,
            "min_managers": 1,
            "max_managers": 2,
            "date_of_event": "20/01/2025 to 21/01/2025",
            "age_category": "18 to 25",
            "docs_required": "ID Proof",
        },
        "3v3 Basketball Women [Open]": {
            "gender": "female",
            "price": 1_770,
            "event_type": "team",
            "min_participants": 4,
            "max_participants": 4,
            "min_managers": 1,
            "max_managers": 2,
            "date_of_event": "20/01/2025 to 21/01/2025",
            "age_category": "18 to 25",
            "docs_required": "ID Proof",
        },
        "5v5 Basketball Men [Open]": {
            "gender": "Male",
            "price": 4_720,
            "event_type": "team",
            "min_participants": 5,
            "max_participants": 12,
            "min_managers": 0,
            "max_managers": 2,
            "date_of_event": "22/01/2025 to 26/01/2025",
            "age_category": "18 to 25",
            "docs_required": "ID Proof",
        },
        "5v5 Basketball Women [Open]": {
            "gender": "female",
            "price": 3_540,
            "event_type": "team",
            "min_participants": 5,
            "max_participants": 12,
            "min_managers": 1,
            "max_managers": 2,
            "date_of_event": "22/01/2025 to 26/01/2025",
            "age_category": "18 to 25",
            "docs_required": "ID Proof",
        },
    },
    "Handball": {
        "Handball [Male]": {
        "gender": "male",
        "price": 1_180,
        "event_type": "team",
        "min_participants": 7,
        "max_participants": 14,
        "min_managers": 1,
        "max_managers": 2,
        "date_of_event": "",
        "age_category": "18 to 30",
        "docs_required": "ID Proof",
    },
    },
    "Squash": {
        "Squash Mixed [Open]": {
        "gender": "open",
        "price": 450,
        "event_type": "single",
        "min_participants": 1,
        "max_participants": 1,
        "min_managers": 0,
        "max_managers": 1,
        "date_of_event": "22/01/2025 to 23/01/2025",
        "age_category": "17 to 27",
        "docs_required": "ID Proof",
    },
    },
     "Martial Arts": {
        "Musical Martial Arts [Open]": {
        "gender": "open",
        "price": 472,
        "event_type": "single",
        "min_participants": 1,
        "max_participants": 1,
        "min_managers": 0,
        "max_managers": 0,
        "date_of_event": "22/01/2025 to 26/01/2025 ",
        "age_category": "17 to 27",
        "docs_required": "ID Proof",
    },
    },

     "Badminton": {
        "Badminton Men's Singles [Male]": {
        "gender": "male",
        "price": 500,
        "event_type": "single",
        "min_participants": 1,
        "max_participants": 1,
        "min_managers": 0,
        "max_managers": 0,
        "date_of_event": "23/01/2025 to  26/01/2025 ",
        "age_category": "17 to 27",
        "docs_required": "ID Proof",
    },

    "Badminton Women's Singles [Female]": {
        "gender": "female",
        "price": 500,
        "event_type": "single",
        "min_participants": 1,
        "max_participants": 1,
        "min_managers": 0,
        "max_managers": 0,
        "date_of_event": "23/01/2025 to  26/01/2025 ",
        "age_category": "17 to 27",
        "docs_required": "ID Proof",
    },

    "Badminton Men's doubles [Male]": {
        "gender": "male",
        "price": 850,
        "event_type": "team",
        "min_participants": 2,
        "max_participants": 2,
        "min_managers": 0,
        "max_managers": 0,
        "date_of_event": "23/01/2025 to  26/01/2025 ",
        "age_category": "17 to 27",
        "docs_required": "ID Proof",
    },

    "Badminton Women's doubles [Female]": {
        "gender": "female",
        "price": 850,
        "event_type": "team",
        "min_participants": 2,
        "max_participants": 2,
        "min_managers": 0,
        "max_managers": 0,
        "date_of_event": "23/01/2025 to  26/01/2025 ",
        "age_category": "17 to 27",
        "docs_required": "ID Proof",
    },

    "Badminton Mixed doubles [Open]": {
        "gender": "open",
        "price": 850,
        "event_type": "team",
        "min_participants": 2,
        "max_participants": 2,
        "min_managers": 0,
        "max_managers": 0,
        "date_of_event": "23/01/2025 to  26/01/2025 ",
        "age_category": "17 to 27",
        "docs_required": "ID Proof",
    },
    },
    "Tennis": {
        "Tennis Men's Singles [Male]": {
        "gender": "male",
        "price": 500,
        "event_type": "single",
        "min_participants": 1,
        "max_participants": 1,
        "min_managers": 0,
        "max_managers": 0,
        "date_of_event": "22/01/2025 to 24/01/2025 ",
        "age_category": "17 to 27",
        "docs_required": "ID Proof",
    },

    "Tennis Men's Doubles [Male]": {
        "gender": "male",
        "price": 1000,
        "event_type": "team",
        "min_participants": 2,
        "max_participants": 2,
        "min_managers": 0,
        "max_managers": 0,
        "date_of_event": "22/01/2025 to 24/01/2025 ",
        "age_category": "17 to 27",
        "docs_required": "ID Proof",
    },

    "Tennis Mixed Doubles [Open]": {
        "gender": "open",
        "price": 1000,
        "event_type": "team",
        "min_participants": 1,
        "max_participants": 1,
        "min_managers": 0,
        "max_managers": 0,
        "date_of_event": "22/01/2025 to 24/01/2025 ",
        "age_category": "17 to 27",
        "docs_required": "ID Proof",
    },
    },

    "Yoga":{
        "Yoga Competetion [Open]": {
        "gender": "open",
        "price": 251,
        "event_type": "team",
        "min_participants": 1,
        "max_participants": 5,
        "min_managers": 0,
        "max_managers": 0,
        "date_of_event": "25/10/2025",
        "age_category": "17 to 27",
        "docs_required": "ID Proof",
    },
    },
}
